---@meta
---@module 'filetree.@types.adapter'
--- Adapter interface every filetree backend must implement.
---
--- All methods are called from feature modules and from the adapter registry.
--- Methods must not throw — return false/nil on failure and log internally.

--- Path-separator note for implementers: callers (cwd_sync, auto_reveal,
--- current_hl, …) source the `path` they pass in from `vim.api.nvim_buf_get_name`
--- / `expand("%:p")`, which return forward-slash paths on some Windows Neovim
--- builds — even though the underlying tree plugin's own node paths may be
--- native-separator (backslash). Any path used as a cache/lookup key inside an
--- adapter (e.g. for get_node_line) MUST be normalized to one consistent form
--- before comparison, or lookups silently miss on Windows. See
--- `key_of()` in adapter/neotree.lua for the reference implementation.
---
---@class FiletreeAdapter
---@field name string                         Unique adapter identifier ("neotree", "nvimtree", …).
---@field is_available  fun(): boolean         True when the underlying plugin is installed and loaded.
---@field is_open       fun(): boolean, integer?   True when the tree window is visible; second return is bufnr.
---@field get_winid     fun(): integer?            Window id of the tree panel, or nil.
---@field get_root_path fun(): string?             Absolute path of the current tree root.
---@field get_current_node fun(): FiletreeNode?    Node under the cursor, or nil.
---@field get_visible_nodes fun(filter?: FiletreeFilterMode): FiletreeNode[]   All currently rendered nodes.
---@field get_node_line    fun(path: string): integer?   1-based line number of `path` in the tree buffer, or nil.
---@field get_bufnr      fun(): integer?               Buffer id of the tree panel, or nil. Every backend in this repo implements it.
---@field expand_node      fun(node: FiletreeNode): boolean
---@field collapse_node    fun(node: FiletreeNode): boolean
---@field open_file        fun(path: string, mode?: FiletreeOpenMode): boolean
---@field open_reveal      fun(path: string, parent_levels?: integer, root_dir?: string): boolean  Open tree and reveal file (root_dir overrides the derived tree root).
---@field set_root         fun(path: string): boolean                            Change the tree root to path.
---@field open_cwd         fun(): boolean                                        Open tree at cwd.
---@field close            fun(): boolean
---@field refresh          fun(): boolean
---@field scroll_to_line   fun(line: integer): boolean
---@field highlight_node   fun(path: string, hl_group: string): boolean          Optional — return false if unsupported.
---@field unhighlight_node fun(path: string): boolean                            Optional — return false if unsupported.
---
--- Optional UI capabilities. Features degrade gracefully when an adapter omits
--- these, so backends can adopt them incrementally.
---
--- **Four of them are declared here and implemented by no backend yet**, which
--- means the guarded branches that call them never run: `get_node_at_line`
--- (git_status, lsp_diagnostics, copy_move, search.filter and ui.size_info all
--- return from their `_render` right after clearing their namespace),
--- `get_expanded_paths`/`expand_paths` (org.session saves and restores no
--- expansion state). They are declared rather than removed because the calling
--- code is written and waiting for them -- see the roadmap entry for the
--- decision that is still open.
---@field filetypes? string[]                    Buffer filetypes this backend's tree uses (e.g. {"neo-tree"}).
---@field hl_groups? table<string, string>       Tree HL group → editor group, for `window_style.highlights_isolate`.
---@field toggle_at? fun(position: FiletreeTreePosition, opts?: FiletreeToggleOpts): boolean  Position-aware toggle; return false if unsupported.
---@field get_position? fun(): FiletreeTreePosition?  Where the tree is (or was last) shown. Must stay
---                     correct while the tree window is CLOSED too (it is the only way to know which
---                     side a sidebar belongs to once it is the sole window and spans the full width);
---                     `util.window` falls back to reading the tree window's column when absent.
---@field redraw? fun(): boolean                 Re-render the current tree from existing state (no filesystem rescan); used by opened_sync.
---@field sign_node? fun(path: string, text: string, hl_group: string): boolean  Place a sign-column marker on a node's line (used by current_hl's icon).
---@field unsign_node? fun(path: string): boolean  Remove a previously placed sign marker.
---@field get_node_at_line? fun(bufnr: integer, linenr: integer): FiletreeNode?  Node rendered on a 0-based buffer line. Implemented by no backend yet.
---@field get_expanded_paths? fun(): string[]|nil  Absolute paths of the currently expanded directories. Implemented by no backend yet.
---@field expand_paths? fun(paths: string[]): boolean  Re-expand the given directories. Implemented by no backend yet.
---@field install_reveal_guard? fun(): nil  Backend-specific guard against a reveal fighting the user's cursor; only the neo-tree adapter has one.

---@alias FiletreeAdapterName "neotree"|"nvimtree"|string

---@alias FiletreeTreePosition
---| "left"     Sidebar on the left
---| "right"    Sidebar on the right
---| "float"    Floating window
---| "current"  In the current window (netrw-style)

---@class FiletreeToggleOpts
---@field reveal? boolean   Reveal the current file when opening.
---@field file?   string?   File to reveal (absolute), when reveal is true.
---@field dir?    string?   Root directory to open at (nil = leave as-is).

---@alias FiletreeFilterMode
---| "all"       All visible nodes (default)
---| "files"     Files only
---| "folders"   Directories only

---@alias FiletreeOpenMode
---| "edit"    Open in current window
---| "split"   Horizontal split
---| "vsplit"  Vertical split
---| "tab"     New tab
---| "preview" Preview (no focus)

return {}
