-- filetree.nvim — machine-readable binding cheatsheet.
--
-- Single entry point to every keymap, `:Filetree` sub-command and autocmd the
-- plugin registers. The data lives in `lua/filetree/bindings/` (keymaps +
-- autocmds) and the command dispatcher TREE (`lua/filetree/commands.lua`), so
-- this file never drifts from what actually runs.
--
-- Human-readable prose lives alongside in docs/BINDINGS/:
--   KEYMAPS.md · USERCOMMANDS.md · AUTOCMDS.md
--
-- Inspect at runtime (plugin must be on the runtimepath):
--   :lua vim.print(require("filetree.bindings").catalog())
--
-- Shape:
--   {
--     command      = "Filetree",          -- active command name
--     keymaps      = { <category> = { { lhs, desc, feature, scope, opt_in? } } },
--     usercommands = { "trash undo", "git refresh", … },  -- sorted paths
--     autocmds     = { { event, feature, desc }, … },
--   }

return require("filetree.bindings").catalog()
