---@module 'filetree.command_descs'
--- One-line descriptions of the `:Filetree` sub-commands, keyed by the space-joined path
--- (`marks show`; the root route of a group is the group name itself).
---
--- `commands.lua` derives its composer routes from the TREE of handlers, which carries no text; the
--- descriptions live here so they can be read without the handlers, and show up in the option float
--- (`lib.nvim.bindings.usercmd.composer.help`) and the generated docs. Source of the wording:
--- docs/BINDINGS/USERCOMMANDS.md.

---@type table<string, string>
return {
  ["breadcrumbs update"] = "Update breadcrumb display",
  ["clipboard clear"] = "Clear clipboard",
  ["clipboard copy"] = "Stage the marked nodes (else the current one) for copy",
  ["clipboard cut"] = "Stage the marked nodes (else the current one) for cut",
  ["clipboard paste"] = "Paste staged nodes",
  ["clipboard show"] = "Show copy/cut clipboard",
  ["clipfiles"] = "Copy the marked nodes (else the current one) to the OS clipboard as files",
  ["copy absolute"] = "Copy absolute path (as $REPOS_DIR/… / $NVIM_CONFIG_DIR/… under an env_roots root)",
  ["copy absolute_raw"] = "Copy the plain absolute path, never folded",
  ["copy buffer_relative"] = "Copy path relative to the buffer open in the editor (./x, ../x)",
  ["copy dirname"] = "Copy absolute parent directory (folded like absolute)",
  ["copy env_rooted"] = "Copy absolute path with an env-var root folded in ($REPOS_DIR/…)",
  ["copy line"] = "Copy path with line number",
  ["copy name"] = "Copy filename",
  ["copy pick"] = "Open format picker",
  ["copy project_relative"] = "Copy path relative to the project root",
  ["copy project_root"] = "Copy the detected project root (cwd-independent; folded like absolute)",
  ["copy relative"] = "Copy relative path",
  ["copy stem"] = "Copy stem (no extension)",
  ["copy uri"] = "Copy as file:// URI",
  ["copymove dry-run"] = "Toggle dry-run for copy/move at runtime — trash and safety always had one",
  ["create"] = "Smart create file or directory",
  ["cwd forget"] = "Drop the policy saved for this project (persist)",
  ["cwd here"] = "Pin the cwd to the node under the cursor",
  ["cwd status"] = "Show the active mode, its scope, root and the cwd",
  ["cwd toggle"] = "Cycle through the configured modes",
  ["cwd unlock"] = "Leave lock mode, back to the previous one",
  ["diff close"] = "Close diff windows",
  ["diff marked"] = "Diff marked nodes",
  ["filelist dirs abs"] = "Copy recursive dir list (absolute)",
  ["filelist dirs rel"] = "Copy recursive dir list (relative)",
  ["filelist files abs"] = "Copy recursive file list (absolute)",
  ["filelist files rel"] = "Copy recursive file list (relative)",
  ["filter"] = "Open the filter input, or apply a query directly",
  ["filter clear"] = "Clear current filter",
  ["git refresh"] = "Refresh git status",
  ["grep"] = "Grep in the node's directory (picker if installed, else rg/grep quickfix)",
  ["handles"] = "List tracked neo-tree watcher handles",
  ["health"] = "Run :checkhealth filetree",
  ["hooks clear"] = "Clear hooks",
  ["hooks events"] = "List registered hook events",
  ["info"] = "Show node info float",
  ["info close"] = "Close info float",
  ["keys"] = "List keys claimed by more than one filetree action",
  ["marks all"] = "Mark all visible nodes",
  ["marks clear"] = "Clear all marks",
  ["marks show"] = "Show floating list",
  ["mdlink"] = "Copy Markdown links for the marked nodes (else the current one)",
  ["mdlink insert"] = "Insert markdown link(s) (marked nodes, else the current one) into the editor window",
  ["mdlink marked"] = "Markdown links for all marked nodes",
  ["mdlink recursive"] = "Markdown links for every file under current node",
  ["mdrefs cancel"] = "Cancel the pending references fix-up (quickfix picker)",
  ["mdrefs confirm"] = "Confirm the pending references fix-up (quickfix picker)",
  ["move"] = "Move the current node (or all marked): prompts for a destination unless one is given",
  ["open"] = "Open the tree focused on a directory or file",
  ["open app"] = "Open with named app",
  ["open pick"] = "Open with app picker",
  ["open system"] = "Open with system default",
  ["openas badd"] = "Add current node to buffer list (no focus switch)",
  ["openas split"] = "Open current node in a horizontal split",
  ["openas tabnew"] = "Open current node in a new tab",
  ["openas vsplit"] = "Open current node in a vertical split",
  ["quickpick"] = "Number the tree's visible entries and open one by typing its number",
  ["quickpick cancel"] = "Leave the mode",
  ["quickpick cwd"] = "Number the tree's entries with the tree rooted at the cwd",
  ["references"] = "List where the file under the cursor (or a path) is referenced; a directory runs refs unused",
  ["refs list"] = "List where the file under the cursor (or a path) is referenced",
  ["refs status"] = "Show engine state: modes, providers, ripgrep, pending undo",
  ["refs undo"] = "Revert the last reference rewrite",
  ["refs unused"] = "List unreferenced asset files under a dir (--all: any file); pick to trash",
  ["rename"] = "Open batch rename buffer",
  ["renamebatch dry-run"] = "Toggle dry-run for the batch rename at runtime",
  ["require"] = 'Copy as require("…") string',
  ["require relative"] = "Copy as relative require",
  ["resize"] = "Set tree window width",
  ["reveal"] = "Reveal current buffer in tree",
  ["reveal pause"] = "Pause auto-reveal for [ms] milliseconds (default 2000)",
  ["reveal resume"] = "Resume auto-reveal",
  ["safety dry-run"] = "Toggle safety dry-run",
  ["safety list"] = "List safety backups",
  ["search"] = "Open live search",
  ["search clear"] = "Clear search highlighting",
  ["session clear"] = "Clear saved session",
  ["session restore"] = "Restore session",
  ["session save"] = "Save current session",
  ["size refresh"] = "Refresh size annotations",
  ["smartrename"] = "Rename with LSP reference update",
  ["source"] = "Pick a neo-tree source from a list, or switch to a named one",
  ["source debug"] = "Print the source list, where it came from, and which sources can load",
  ["source next"] = "Switch to the next neo-tree source (wrapping)",
  ["source pick"] = "Pick a neo-tree source from a floating list",
  ["source prev"] = "Switch to the previous neo-tree source (wrapping)",
  ["symlink"] = "Prompt for a target path, create a symlink/hardlink to it in the current tree directory",
  ["symlink check"] = "Report whether the node/path is a symlink, and whether it's broken",
  ["symlink checkall"] = "Report symlink state of every marked node (else the node under the cursor)",
  ["symlink delete"] = "Remove marked symlinks (else the node under the cursor) via trash — never a non-symlink",
  ["symlink mark"] = "Mark a link source (node/buffer/explicit path), no prompt",
  ["symlink paste"] = "Paste the marked source as a link, kind picked automatically",
  ["symlink repair"] = "If broken, search the filesystem for a new target",
  ["symlink repairall"] = "Repair every broken symlink among the marked nodes",
  ["template"] = "Create file from template — pick a template first",
  ["toggle"] = "Toggle the tree at left, right, float or current (default left), revealing the current file",
  ["trash dry-run"] = "Toggle dry-run mode",
  ["trash history"] = "Show trash history",
  ["trash undo"] = "Undo last trash operation",
  ["traverse down"] = "Set current dir as root",
  ["traverse up"] = "Navigate to parent directory",
  ["watcher enter"] = "Enter watcher quarantine",
  ["watcher exit"] = "Exit watcher quarantine",
}
